#### Random sampling (numpy.random)
###### 1.rand(d0, d1, ..., dn)	Random values in a given shape.
###### 2.randn(d0, d1, ..., dn)	Return a sample (or samples) from the “standard normal” distribution.
###### 3.randint(low[, high, size, dtype])	Return random integers from low (inclusive) to high (exclusive).
###### 4.random_integers(low[, high, size])	Random integers of type np.int between low and high, inclusive.
###### 5.random_sample([size])	Return random floats in the half-open interval [0.0, 1.0).
###### 6.random([size])	Return random floats in the half-open interval [0.0, 1.0).
###### 7.ranf([size])	Return random floats in the half-open interval [0.0, 1.0).
###### 8.sample([size])	Return random floats in the half-open interval [0.0, 1.0).
###### 9.bytes(length)	Return random bytes.
#### Permutations
###### 1. shuffle(x)	Modify a sequence in-place by shuffling its contents.
###### 2. permutation(x)	Randomly permute a sequence, or return a permuted range.

###### 1. Import the numpy package under the name np

In [11]:
import numpy as np

###### 2. Print the numpy version and the configuration

In [11]:
print(np.__version__) # Версия 
print(np.show_config()) # Конфигурация библиотеки
print(dir(np)) #Возвращает имена [переменных], доступные в локальной области, либо атрибуты указанного объекта в алфавитном порядке.   
               #               1. Если объект является модулем, список будет содержать имена атрибутов модуля;
               #               2. Если объект является типом или классом, список будет содержать имена атрибутов данного 
               #                  объекта и его родителей (вычисляются рекурсивно).
               #               
               #               3. В других случаях список будет содержать имена атрибутов самого объекта, его класса, 
               #                  и классов-родителей (вычисляются рекурсивно)
print ()                
print(np.__file__)

1.12.0
lapack_mkl_info:
  NOT AVAILABLE
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
    language = c
blas_opt_info:
    libraries = ['openblas', 'openblas']
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
    language = c
openblas_info:
    libraries = ['openblas', 'openblas']
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
    language = c
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    define_macros = [('HAVE_CBLAS', None)]
    library_dirs = ['/usr/local/lib']
    language = c
None
['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'I

###### 3. Create a null vector of size 10

In [16]:
print(np.zeros(10))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


###### 4. How to find the memory size of any array

In [21]:
import sys
a = [1,2,3,4,5,6]
print(sys.getsizeof(a))
b = np.ones(100)
print(b.nbytes)
print(sys.getsizeof(b))

112
800
896


###### 5.Create a null vector of size 10 but the fifth value which is 1 

In [23]:
array = np.zeros(10)
array[5] = 1
print(array)

[ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]


###### 6. How to get the documentation of the numpy add function from the command line?

In [ ]:
python -c 'import numpy as np; help(np.add)'

###### 7. Create a vector with values ranging from 10 to 49

In [15]:
np.random.randint(10,49,(5))

array([28, 15, 43, 36, 43])

###### 8. Reverse a vector (first element becomes last)

In [27]:
array = np.random.randint(10,20, (10))
print(array)
array = array[::-1]
print(array)
array = list(array)
array.reverse()
print(np.array(array))

[19 14 15 14 12 11 19 19 10 13]
[13 10 19 19 11 12 14 15 14 19]
[19 14 15 14 12 11 19 19 10 13]


###### 9. Create a 3x3 matrix with values ranging from 0 to 8 

In [28]:
array = np.random.randint(0,8, (3,3))
array

array([[7, 0, 7],
       [1, 3, 1],
       [6, 1, 5]])

###### 10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [33]:
array = np.array([1,2,0,0,4,0])
print(np.nonzero(array))
non_zero_index = [index for index,value in enumerate(array) if value != 0]
print(non_zero_index)

(array([0, 1, 4]),)
[0, 1, 4]


###### 11. Create a 3x3 identity matrix

In [39]:
np.eye(3,3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

###### 12. Create a 3x3x3 array with random values

In [49]:
np.random.random((3,3,3))

array([[[ 0.8425613 ,  0.79306154,  0.81265525],
        [ 0.63001257,  0.56154447,  0.11626497],
        [ 0.67016404,  0.62198367,  0.23771832]],

       [[ 0.92912209,  0.92445008,  0.75059059],
        [ 0.86269461,  0.04882197,  0.61452499],
        [ 0.79908655,  0.80175343,  0.78845164]],

       [[ 0.37911241,  0.67370139,  0.67301666],
        [ 0.85432116,  0.31092971,  0.14955226],
        [ 0.9684352 ,  0.08980489,  0.42605528]]])

###### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [54]:
array = np.random.random((10,10))
max_value = array.max()
min_value = array.min()

###### 14. Create a random vector of size 30 and find the mean value

In [56]:
array = np.random.randint(0,20,(30))
print(array.mean())

9.43333333333


###### 15. Create a 2d array with 1 on the border and 0 inside

In [61]:
X = np.ones((5,5))
X
X[1:-1, 1:-1] = 0
X

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [65]:
X = np.zeros((5,5))
a,b  = X.shape
for i in range(a):
    for j in range(b):
        if i == 0 or i == a-1:
            X[i,j] = 1
        if j == 0 or j == b-1:
            X[i,j] = 1
X

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

###### 16. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [69]:
np.diag([1,2,3,4] , k = -1 ) # numpy.diag(v, k=0) v - вектор k = 0 -диагональ ; k = -1 - поддиаагональ , k=1 - наддиагональ 

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [76]:
np.diag([x + 1 for x in list(range(4))], k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

###### 17. Normalize a 5x5 random matrix

In [84]:
array = np.random.randint(0,50,(5,5))
print(array)
max_value , min_value = array.max(), array.min()
array = (array - min_value) / (max_value - min_value) 
print(array)

[[43 12 22  0 39]
 [31  2  3  0 20]
 [ 3 14 11 26 10]
 [41 38 31 46  4]
 [45 25 46 46 46]]
[[ 0.93478261  0.26086957  0.47826087  0.          0.84782609]
 [ 0.67391304  0.04347826  0.06521739  0.          0.43478261]
 [ 0.06521739  0.30434783  0.23913043  0.56521739  0.2173913 ]
 [ 0.89130435  0.82608696  0.67391304  1.          0.08695652]
 [ 0.97826087  0.54347826  1.          1.          1.        ]]


###### 18.Create a custom dtype that describes a color as four unisgned bytes (RGBA)

In [85]:
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

numpy.void